### ISSUE TITLE
Selected game page not loading

### ISSUE THREAD

**Issue by Armadillidiid** [nekusu/shopping-cart#1]
When I select a game from the store menu , the selected game page loads forever. Also, I get a Cross-Origin Request  error in console.
![Screenshot_20230204_163724](https://user-images.githubusercontent.com/86387828/216776181-c54936c8-c118-4697-bbd2-765102a5c17d.png)

**Comment by nekusu** [comment]
Thank you for the report.

It looks like the monthly API limit of 20k requests has been reached, if you are running the repository locally you need set your own API key in order to not exceed my request limit.

I updated the repo and added some instructions on how to do it in the README file.

If that's not the case, the number of requests will be renewed on February 11 anyway.
